# Generated by Django 2.2.1 on 2019-05-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('pair_name', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('state', models.CharField(default='OFF', max_length=2)),
            ],
        ),
    ]
