# Generated by Django 2.2.1 on 2019-05-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='state',
            field=models.CharField(default='OFF', max_length=3),
        ),
    ]
