# Generated by Django 2.2.1 on 2019-05-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0002_auto_20190516_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='state',
            field=models.CharField(choices=[('ON', 'on'), ('OFF', 'off')], default='OFF', max_length=3),
        ),
    ]
