# Generated by Django 2.2.1 on 2019-05-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0003_auto_20190519_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pair',
            old_name='state',
            new_name='status',
        ),
        migrations.AddField(
            model_name='pair',
            name='historical',
            field=models.CharField(choices=[('absent', 'absent'), ('building', 'building'), ('full', 'full')], default='absent', max_length=8),
        ),
    ]
