# Generated by Django 2.2.1 on 2019-06-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinancePair',
            fields=[
                ('name', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('get_data', models.CharField(choices=[('ON', 'on'), ('OFF', 'off')], default='OFF', max_length=3)),
                ('status', models.CharField(default='absent', max_length=8)),
                ('last_stored_candle', models.DateTimeField(blank=True, null=True)),
                ('last_change_by_PID', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'binance_pairs',
            },
        ),
    ]
