version: '3.7'

services:
  db:
    image: postgres:11.2-alpine
    env_file:
      - "$env_file"
    ports:
      - "$DB_PORT:5432"
    volumes:
      - dev_pg:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    logging:
      driver: none
    ports:
      - "$PGADMIN_PORT:80"
    env_file:
      - "$env_file"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - backend

  controller:
    build: ../controller
    ports:
      - "$controller_PORT:8080"
    env_file:
      - "$env_file"
    depends_on:
      - db
    networks:
      - backend

  binancedatastoragedaemon:
    build: ../BinanceDataStorageDaemon
    env_file:
      - "$env_file"
    volumes:
      - BDSD_LOG:/BinanceDataStorageDaemon/logs
    depends_on:
      - db
      - controller
    networks:
      - backend

networks:
  backend:
    driver: bridge
  
volumes:
  dev_pg:
    driver: local
    name: dev_pg
  pgadmin:
    driver: local
    name: pgadmin
  BDSD_LOG:
    driver: local
    name: BDSD_LOG