version: '3.7'

services:
  
  es_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    ports:
      - 9200:9200
    container_name: "${operation_name}_esdb_dev"
    volumes:
      - "esdata:${PWD}/dev/src/elasticsearch/data"

volumes:
  esdata:
    driver: local